import * as CONTROLLERS from './controllers';

export const ROOT = '/node' as const;

export const REST_API = {
    AUTH: {
        AUTHENTICATION: `${ROOT}/${CONTROLLERS.AUTH_CONTROLLER}/${CONTROLLERS.AUTH_ROUTES.AUTHENTICATION}`,
    },
    USERS: {
        POST: `${ROOT}/${CONTROLLERS.USERS_CONTROLLER}/${CONTROLLERS.USERS_ROUTES.POST}`,
        ADD: `${ROOT}/${CONTROLLERS.USERS_CONTROLLER}/${CONTROLLERS.USERS_ROUTES.ADD}`,
        REMOVE: `${ROOT}/${CONTROLLERS.USERS_CONTROLLER}/${CONTROLLERS.USERS_ROUTES.REMOVE}`,
    },
    SQUID: {
        START: `${ROOT}/${CONTROLLERS.SQUID_CONTROLLER}/${CONTROLLERS.SQUID_ROUTES.START}`,
        STOP: `${ROOT}/${CONTROLLERS.SQUID_CONTROLLER}/${CONTROLLERS.SQUID_ROUTES.STOP}`,
        RESTART: `${ROOT}/${CONTROLLERS.SQUID_CONTROLLER}/${CONTROLLERS.SQUID_ROUTES.RESTART}`,
        CONFIG: `${ROOT}/${CONTROLLERS.SQUID_CONTROLLER}/${CONTROLLERS.SQUID_ROUTES.CONFIG}`,
    },
}